### PR TITLE
Add Typescript + Vue template

### PR DESCRIPTION
**Pull request by oatspear**
I believe this PR is missing an upgrade to eslint 9+, but I am still not exactly sure what exact changes that entails. I tried manually converting the configuration file, using example games as a basis, but I am not exactly sure which objects need to be imported from Vue packages.

### CODE REVIEW

**Comment by oatspear** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by oatspear** [comment]
recheck

**Comment by Gongreg** [comment]
Hey @oatspear , thank you for the contribution.
I've updated your PR to use eslint9 config. Will check if everything passes and then release it.

**Comment by oatspear** [comment]
Sounds great. Thanks!

**Review by Gongreg — APPROVED** [review]

**Comment by oatspear** [comment]
Just a note @Gongreg : I am copying the changes you made to my own repository, and the `devDependency` on Dusk 4.20 in this template causes the following import to fail.

```js
import dusk from "dusk-games-sdk/vite"
```

Upgrading to Dusk 4.21 solves it.

```diff
    "dependencies": {
-     "dusk-games-sdk": "^4.20.2",
+     "dusk-games-sdk": "^4.21.13",
      "vue": "^3.4.29"
    },
```

**Pull request merged**
