### PR TITLE
feat: allow export statements in logic.js

### PR DESCRIPTION
**Pull request by oblador**
This PR updates the linting config to allow safe export statements for code re-use with client end code.

### CODE REVIEW

**Comment by helios1138** [comment]
@oblador How do we then guarantee that there won't be exports in the final bundle for upload? Or are we actually ok with this?

**Comment by oblador** [comment]
Why would an export of a local variable be problematic?

**Comment by helios1138** [comment]
Also, AFAIK importing from logic.js inevitably means that initLogic() would be called twice now.

**Comment by helios1138** [comment]
> Why would an export of a local variable be problematic?

Good question. Why did we prohibit it in the first place?

**Comment by oblador** [comment]
Because `export ... from` is problematic and I didn't think of any good other uses for export (but I do now 😇)

**Comment by oblador** [comment]
> Also, AFAIK importing from logic.js inevitably means that initLogic() would be called twice now.

If your client code imports from logic.js you don't have to add it as a script tag, but even if you did all other module systems that I know makes sure that a file is only evaluated once.

**Review by helios1138 — APPROVED** [review]

**Review by bfelbo — APPROVED** [review]
🥳

**Pull request merged**
