### PR TITLE
feat: detect assets

### PR DESCRIPTION
**Pull request by Gongreg**
Do not allow asset files to be imported inside logic.

### CODE REVIEW

**Comment by kevglass** [comment]
This is going to break some of my games. I use SVG for instance as an input to build game physics models for Scorched Turf. Think this would be nice to be able to turn off.

**Comment by bfelbo** [comment]
AFAIK, the SVG in Scorched Turf is inlined into logic.js. Perhaps we can make the detection more intelligent to not flag inlined assets and explain in the error msg how to inline assets into logic.js if needed for that game?

**Comment by bfelbo** [comment]
I.e. I'd suggest making the detection more intelligent rather than adding a flag :)

**Comment by Gongreg** [comment]
@bfelbo , we've looked into Kev example and in his case there is no error/warning there. Currently asset detection is very basic, so in case user uses inline param, we won't understand that this is an asset, because `png?inline` !== `png`.

**Comment by bfelbo** [comment]
Sounds great 👍

**Pull request merged**
