### PR TITLE
build: build workspace packages in prepare script

### PR DESCRIPTION
**Pull request by oblador**
To test:

```bash
git clean -f -x -d # clean up git-ignored files and directories
yarn
yarn lint
```

Before this PR it should fail due to the lint package not being built, with this one it should pass.

### CODE REVIEW

**Comment by helios1138** [comment]
@oblador so if I change something in the ESlint package that I want to test in the CLI, I should also re-run `yarn build` in root, right? If yes, can we mention this in the README?

**Comment by oblador** [comment]
That's correct, added a section on developing in the eslint config readme.

**Review by helios1138 — APPROVED** [review]
👍

**Review by bfelbo — APPROVED** [review]
LGTM! 🥳

**Pull request merged**
